apiVersion: v1
kind: Namespace
metadata:
  name: sdfsdffsd-staging
  labels:
    environment-id: env_02bb2f9f-88e5-4f0f-b592-53433a3776e7
    project-id: project_f1558ebe-025d-4ce8-b9bc-9bd445397821
    project-name: sdfsdffsd
    environment-name: staging
    organization-id: org_9aad87d0-abbc-48f9-9038-002316f0475a
